### ISSUE TITLE
HVA crashes when dc network isn't set in the database

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#448]
When attempting to start an instance without setting the dc network, HVA will crash with the following stacktrace.

    I, [2014-09-29T17:43:22.299404 #3310]  INFO -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Detached partition from devmapper: /dev/mapper/loop0p1
    I, [2014-09-29T17:43:22.299540 #3310]  INFO -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Executing command: udevadm settle
    D, [2014-09-29T17:43:22.303887 #3310] DEBUG -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Command Result: success (exit code=0)
    Command PID: 4788
    I, [2014-09-29T17:43:22.304113 #3310]  INFO -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Executing command: losetup -d /dev/loop0
    D, [2014-09-29T17:43:22.309187 #3310] DEBUG -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Command Result: success (exit code=0)
    Command PID: 4789
    I, [2014-09-29T17:43:22.309367 #3310]  INFO -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Detached from loop device: /dev/loop0
    E, [2014-09-29T17:43:22.329175 #3310] ERROR -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: NoMethodError undefined method `[]' for nil:NilClass from /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/linux_hypervisor.rb:63:in `block in check_interface'
    2014-09-29 17:43:22 JobContext thr=JobWorker[0/1] [ERROR]: Job failed a3f3c968e97693788298d38d3e02f57f971cb323 [ run_local_store ]: undefined method `[]' for nil:NilClass
    2014-09-29 17:43:22 JobContext thr=JobWorker[0/1] [ERROR]: Caught NoMethodError: undefined method `[]' for nil:NilClass
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/linux_hypervisor.rb:63:in `block in check_interface'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/linux_hypervisor.rb:58:in `each'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/linux_hypervisor.rb:58:in `check_interface'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:178:in `call'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:178:in `invoke!'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:249:in `invoke'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/rpc/hva_handler.rb:187:in `check_interface'
    /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/rpc/hva_handler.rb:318:in `block in <class:HvaHandler>'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/runner/rpc_server.rb:69:in `instance_eval'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/runner/rpc_server.rb:69:in `block in job'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/rack/proc.rb:25:in `instance_eval'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/rack/proc.rb:25:in `call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/rack/map.rb:52:in `call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/rack/map.rb:52:in `call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/rack/builder.rb:36:in `call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/rack/job.rb:59:in `block (2 levels) in call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/node_modules/job_worker.rb:67:in `call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/node_modules/job_worker.rb:67:in `block in start'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/thread_pool.rb:32:in `call'
    /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.19/lib/isono/thread_pool.rb:32:in `block (2 levels) in initialize'
    I, [2014-09-29T17:43:22.329752 #3310]  INFO -- HvaHandler: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Instance UUID: i-5e07vvjy: teminating instance
    I, [2014-09-29T17:43:22.330344 #3310]  INFO -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Executing command: vzctl stop i-5e07vvjy
    D, [2014-09-29T17:43:22.349625 #3310] DEBUG -- Openvz: Session ID: a3f3c968e97693788298d38d3e02f57f971cb323: Command Result: fail (exit code=21)

The problem is this line of code right here. https://github.com/axsh/wakame-vdc/blob/master/dcmgr/lib/dcmgr/drivers/linux_hypervisor.rb#L63

This could be a quick fix by adding a nil check but we really should check this as early as the API call. When there's a faulty state, we should fail gracefully asap.

**Comment by Metallion** [comment]
Directories were refactored. The line of code in question is this: https://github.com/axsh/wakame-vdc/blob/master/dcmgr/lib/dcmgr/drivers/hypervisor/linux_hypervisor.rb#L63

**Comment by Metallion** [comment]
# Solution

1) Add a nilcheck in the above line of code

2) Add a check to the API and when starting a new instance and fail gracefully if dc_network is not set

**Comment by Metallion** [comment]
Has been done. https://github.com/axsh/wakame-vdc/pull/505
