### ISSUE TITLE
Check if "vdc-manage image del" works

### ISSUE THREAD

**Issue by triggers** [axsh/wakame-vdc#507]

**Comment by triggers** [comment]
for example:
```
/ssh:niibm111: #$ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image show
UUID         Account ID  Service Type  Name                       Boot Type  Arch
wmi-lucid5d  a-shpoolxx  std           Ubuntu 10.04 (Lucid Lynx)  local      x86_64
wmi-lbimage  a-shpoolxx  std           Load Balancer Image        local      x86_64
/ssh:niibm111: #$ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image del wmi-lbimage
/ssh:niibm111: #$ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image show
UUID         Account ID  Service Type  Name                       Boot Type  Arch
wmi-lucid5d  a-shpoolxx  std           Ubuntu 10.04 (Lucid Lynx)  local      x86_64
wmi-lbimage  a-shpoolxx  std           Load Balancer Image        local      x86_64
/ssh:niibm111: #$
```

**Comment by triggers** [comment]
Just noticed wmi-lbimage does not show in the web gui, so maybe it is a bug in show.

**Comment by triggers** [comment]
Indeed, it was deleted:
```
/opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image show wmi-lbimage
+ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image show wmi-lbimage
UUID: wmi-lbimage
Name: Load Balancer Image
Account ID: a-shpoolxx
Boot Type: local
Arch: x86_64
Is Public: false
State: deleted
Service Type: std
Cacheable: false
OS Type: linux
Parent Image ID: 
Create: 2015-02-09 14:20:18 UTC
Update: 2015-02-12 11:52:50 UTC
Delete: 2015-02-12 11:52:50 UTC
Features:
{}
Instance Model Name: 
```

**Comment by triggers** [comment]
But we can delete it again...correct behavior?
```
/ssh:niibm111: #$ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image del wmi-lbimage
/ssh:niibm111: #$ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage image del wmi-lbimageabc
ERROR: Unknown UUID: 'wmi-lbimageabc'. (/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/cli/errors.rb:13:in `raise')
```

And note, wmi-lbimage is not available for use....correct behavior?
```
/ssh:niibm111: #$ /opt/axsh/wakame-vdc/dcmgr/bin/vdc-manage backupobject add --uuid bo-lbimage --display-name 'lb image' --storage-id bkst-local --object-key lb-150212-193606.kvm.md.raw.tar.gz --size 32212254720 --allocation-size 765927457 --container-format tgz --checksum d7468688adcb78cc6874f4d763739de6
ERROR: Duplicate UUID: bo-lbimage already exists (/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/models/base_new.rb:78:in `before_create')
```
