### ISSUE TITLE
collector crashes when getting an alarm event

### ISSUE THREAD

**Issue by hansode** [axsh/wakame-vdc#584]
### Problem

Sometimes collector was killed when getting an alarm event.

Steps to reproduce:

+ Setup dummy based hva
+ Run `./t.network_vif_monitor.port.sh`

`/var/log/wakame-vdc/collector.log`:

```
15:06:41 2015-05-20 15:02:19 JobContext thr=JobWorker[0/1] [INFO]: Job complete 7752d2d5a15663ab3aa5c8699c36f0c7d92a3c1d (Local ID: 7752d2d5a15663ab3aa5c8699c36f0c7d92a3c1d)[ schedule_instance ]: 0.039457626 sec
15:06:41 I, [2015-05-20T15:02:19.336739 #1962]  INFO -- AlarmCollector: event_caught: ["i-4olbrf92"]
15:06:41 I, [2015-05-20T15:02:22.972204 #1962]  INFO -- HvaCollector: finalize_instance(i-4olbrf92) terminated at=2015-05-20 06:02:22 UTC
15:06:41 I, [2015-05-20T15:02:22.987925 #1962]  INFO -- AlarmCollector: event_caught: ["i-4olbrf92"]
15:06:41 I, [2015-05-20T15:02:22.988434 #1962]  INFO -- EventHook: event caught: ["i-4olbrf92"]
15:06:41 I, [2015-05-20T15:02:22.989145 #1962]  INFO -- AlarmCollector: event_caught: ["i-4olbrf92"]
15:06:41 2015-05-20 15:02:26 Node thr=#<Thread:0x007ff688193d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=collector.master, token=39bb2
```

` /var/log/wakame-vdc/hva.log`

```
15:06:42 2015-05-20 15:02:23 JobContext thr=JobWorker[0/1] [INFO]: Job complete 79b226002fe8ab9c3472c8b84e5ee68a1725d0b2 (Local ID: 79b226002fe8ab9c3472c8b84e5ee68a1725d0b2)[ delete_alarm ]: 0.063245579 sec
15:06:42 2015-05-20 15:05:36 ThreadPool thr=InstanceMonitor[0/1] [ERROR]: Caught Isono::NodeModules::RpcChannel::RpcError: timeout
15:06:42 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/rpc_channel.rb:466:in `wait'
15:06:42 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/rpc_channel.rb:153:in `request'
15:06:42 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/instance_monitor.rb:31:in `check_instance'
15:06:42 	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/instance_monitor.rb:12:in `block (3 levels) in <class:InstanceMonitor>'
15:06:42 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `call'
15:06:42 	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `block (2 levels) in initialize'
```

**Comment by hansode** [comment]
collector crasher scripts:

+ [wakame-vdc/t.log.alarm.sh at develop · axsh/wakame-vdc](https://github.com/axsh/wakame-vdc/blob/develop/client/mussel/test/integration/v12.03/rwx/t.log.alarm.sh)
+ [wakame-vdc/t.network_vif_monitor.port.sh at develop · axsh/wakame-vdc](https://github.com/axsh/wakame-vdc/blob/develop/client/mussel/test/integration/v12.03/rwx/t.network_vif_monitor.port.sh)

**Comment by hansode** [comment]
crasher functions:

+ `t.network_vif_monitor.port.sh`
   + [test_instance_monitoring_enable](https://github.com/axsh/wakame-vdc/blob/develop/client/mussel/test/integration/v12.03/rwx/t.network_vif_monitor.port.sh#L26-L31)
+ `t.log.alarm.sh`
   + [test_destroy_alarm](https://github.com/axsh/wakame-vdc/blob/develop/client/mussel/test/integration/v12.03/rwx/t.log.alarm.sh#L74-L77)

**Comment by hansode** [comment]
> t.network_vif_monitor.port.sh
> test_instance_monitoring_enable

```
function test_instance_monitoring_enable() {
  local monitoring="enabled=true"

  run_cmd instance_monitoring set_enable ${instance_uuid}
  assertEquals 0 $?
}
```

**Comment by hansode** [comment]
https://github.com/axsh/wakame-vdc/blob/develop/client/mussel/v12.03.d/instance_monitoring.sh#L69-L79

```
task_set_enable() {
  local namespace=$1 cmd=$2 uuid=$3
  [[ -n "${namespace}" ]] || { echo "[ERROR] 'namespace' is empty (${BASH_SOURCE[0]##*/}:${LINENO})" >&2; return 1; }
  [[ -n "${cmd}"       ]] || { echo "[ERROR] 'cmd' is empty (${BASH_SOURCE[0]##*/}:${LINENO})" >&2; return 1; }
  [[ -n "${uuid}"      ]] || { echo "[ERROR] 'uuid' is empty (${BASH_SOURCE[0]##*/}:${LINENO})" >&2; return 1; }

  call_api -X PUT $(urlencode_data \
    $(add_param monitoring hash) \
   ) \
   $(base_uri)/instances/${uuid}.$(suffix)
}
```

**Comment by hansode** [comment]
https://github.com/axsh/wakame-vdc/blob/develop/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb#L805-L824

```
    # Update a monitor parameters.
    put '/:monitor_id' do
      @instance.monitor_item(params[:monitor_id]) || raise(E::UnknownUUIDResource, params[:monitor_id])

      monitor = {}
      unless params[:enabled].blank?
        monitor[:enabled] = (params[:enabled] == 'true')
      end

      monitor[:title] = params[:title] unless params[:title].blank?
      monitor[:params] = params[:params] unless params[:params].blank?
      @instance.update_monitor_item(params[:monitor_id], monitor)

      on_after_commit do
        Dcmgr.messaging.event_publish("instance.monitoring.refreshed",
                                      :args=>[{:instance_id=>@instance.canonical_uuid, :monitor_id=>params[:monitor_id]}])
      end

      respond_with(R::InstanceMonitorItem.new(@instance, params[:monitor_id]).generate)
    end
```

**Comment by hansode** [comment]
https://github.com/axsh/wakame-vdc/blob/develop/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb#L575-L584

```
    if set_monitoring_parameters(instance)
      on_after_commit do
        # instance.monitoring.refreshed is published only when the instance
        # has been running already.
        if instance.state.to_s != 'init'
          Dcmgr.messaging.event_publish("instance.monitoring.refreshed",
                                        :args=>[{:instance_id=>instance.canonical_uuid}])
        end
      end
    end
```

**Comment by hansode** [comment]
> t.log.alarm.sh
> test_destroy_alarm

```
function test_destroy_alarm() {
  run_cmd alarm destroy  ${alarm_uuid} >/dev/null
  assertEquals 0 $?
}
```

**Comment by hansode** [comment]
https://github.com/axsh/wakame-vdc/blob/develop/dcmgr/lib/dcmgr/endpoints/12.03/alarms.rb#L131-L141

```
  delete '/:id' do
    al = find_by_uuid(:Alarm, params[:id])
    al = al.destroy

    on_after_commit do
      i = find_by_uuid(:Instance, al.resource_id)
      Dcmgr.messaging.submit(alarm_endpoint(al.metric_name, i.host_node.node_id), 'delete_alarm', al.canonical_uuid)
    end

    respond_with([al.canonical_uuid])
  end
```

**Comment by hansode** [comment]
when crashing collector, nwmongw also crashing.

```
14:38:50 2015-07-17 14:34:35 Node thr=#<Thread:0x007fba24193d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=4bdb3
14:38:50 I, [2015-07-17T14:36:36.633046 #11407]  INFO -- MonitoringGateway: Refreshing monitoring configuration for i-fr0l4c5s
```

```
18:09:35 2015-07-17 18:05:20 Node thr=#<Thread:0x007f7dd7593d58> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=90561
18:09:35 I, [2015-07-17T18:07:21.793996 #11363]  INFO -- MonitoringGateway: Refreshing monitoring configuration for i-jabzazqx
```

**Comment by hansode** [comment]
nwmongw crashes when getting an alarm event.

**Comment by hansode** [comment]
when `hva` ran `delete_alarm`, `collector` and `nwmongw` will be crashed!!!

hva.log:

```
[centos@wakame-vdc-1box ~]$ grep delete_alarm /var/log/wakame-vdc/hva.log
2015-07-20 20:54:49 JobContext thr=JobWorker[0/1] [INFO]: Job start 8d50f0c159488e1361e73d7ec3c1b3588bce2e79 (Local ID: 8d50f0c159488e1361e73d7ec3c1b3588bce2e79)[ delete_alarm ]
2015-07-20 20:54:50 JobContext thr=JobWorker[0/1] [INFO]: Job complete 8d50f0c159488e1361e73d7ec3c1b3588bce2e79 (Local ID: 8d50f0c159488e1361e73d7ec3c1b3588bce2e79)[ delete_alarm ]: 0.051232583 sec
2015-07-20 20:56:33 JobContext thr=JobWorker[0/1] [INFO]: Job start 08e40ae82856202009df6b4d79ad963e32cb1518 (Local ID: 08e40ae82856202009df6b4d79ad963e32cb1518)[ delete_alarm ]
2015-07-20 20:56:33 JobContext thr=JobWorker[0/1] [INFO]: Job complete 08e40ae82856202009df6b4d79ad963e32cb1518 (Local ID: 08e40ae82856202009df6b4d79ad963e32cb1518)[ delete_alarm ]: 0.068219117 sec
2015-07-20 23:42:13 JobContext thr=JobWorker[0/1] [INFO]: Job start 835b2a41b8f77b0794d70aef15a10efaf12888e1 (Local ID: 835b2a41b8f77b0794d70aef15a10efaf12888e1)[ delete_alarm ]
2015-07-20 23:42:13 JobContext thr=JobWorker[0/1] [INFO]: Job complete 835b2a41b8f77b0794d70aef15a10efaf12888e1 (Local ID: 835b2a41b8f77b0794d70aef15a10efaf12888e1)[ delete_alarm ]: 0.074318226 sec
2015-07-20 23:46:03 JobContext thr=JobWorker[0/1] [INFO]: Job start 410cac6eb88fc7f0551ff2f7ae0ed94ccaf6c299 (Local ID: 410cac6eb88fc7f0551ff2f7ae0ed94ccaf6c299)[ delete_alarm ]
2015-07-20 23:46:03 JobContext thr=JobWorker[0/1] [INFO]: Job complete 410cac6eb88fc7f0551ff2f7ae0ed94ccaf6c299 (Local ID: 410cac6eb88fc7f0551ff2f7ae0ed94ccaf6c299)[ delete_alarm ]: 0.075706827 sec
2015-07-20 23:53:48 JobContext thr=JobWorker[0/1] [INFO]: Job start b3d7991eebb17a214a9074d8144f530736ce2f9e (Local ID: b3d7991eebb17a214a9074d8144f530736ce2f9e)[ delete_alarm ]
2015-07-20 23:53:49 JobContext thr=JobWorker[0/1] [INFO]: Job complete b3d7991eebb17a214a9074d8144f530736ce2f9e (Local ID: b3d7991eebb17a214a9074d8144f530736ce2f9e)[ delete_alarm ]: 0.10201143 sec
2015-07-21 00:03:39 JobContext thr=JobWorker[0/1] [INFO]: Job start 6a165858a72746485a5edf77e3026285042e346a (Local ID: 6a165858a72746485a5edf77e3026285042e346a)[ delete_alarm ]
2015-07-21 00:03:39 JobContext thr=JobWorker[0/1] [INFO]: Job complete 6a165858a72746485a5edf77e3026285042e346a (Local ID: 6a165858a72746485a5edf77e3026285042e346a)[ delete_alarm ]: 0.107990743 sec
2015-07-21 00:09:59 JobContext thr=JobWorker[0/1] [INFO]: Job start f423ac426e7fadbeac2a30943406c078ae906db5 (Local ID: f423ac426e7fadbeac2a30943406c078ae906db5)[ delete_alarm ]
2015-07-21 00:09:59 JobContext thr=JobWorker[0/1] [INFO]: Job complete f423ac426e7fadbeac2a30943406c078ae906db5 (Local ID: f423ac426e7fadbeac2a30943406c078ae906db5)[ delete_alarm ]: 0.103119687 sec
2015-07-21 00:16:19 JobContext thr=JobWorker[0/1] [INFO]: Job start 5db080440a81d14047342483b99d693d8d59564b (Local ID: 5db080440a81d14047342483b99d693d8d59564b)[ delete_alarm ]
2015-07-21 00:16:19 JobContext thr=JobWorker[0/1] [INFO]: Job complete 5db080440a81d14047342483b99d693d8d59564b (Local ID: 5db080440a81d14047342483b99d693d8d59564b)[ delete_alarm ]: 0.105455012 sec
2015-07-21 00:22:39 JobContext thr=JobWorker[0/1] [INFO]: Job start 1f729937fe17d71410837c0438e961de50c591e8 (Local ID: 1f729937fe17d71410837c0438e961de50c591e8)[ delete_alarm ]
2015-07-21 00:22:39 JobContext thr=JobWorker[0/1] [INFO]: Job complete 1f729937fe17d71410837c0438e961de50c591e8 (Local ID: 1f729937fe17d71410837c0438e961de50c591e8)[ delete_alarm ]: 0.145465663 sec
```

nwmongw.log:

```
2015-07-21 00:00:38 Node thr=#<Thread:0x007f423cd93d40> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=0de60
2015-07-21 00:03:42 Node thr=#<Thread:0x007f9ac1193d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=fbef7
2015-07-21 00:06:52 Node thr=#<Thread:0x007fa16e993d58> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=8fe90
2015-07-21 00:10:02 Node thr=#<Thread:0x007fe000993d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=735e0
2015-07-21 00:13:12 Node thr=#<Thread:0x007fab8c993d58> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=6dcf9
2015-07-21 00:16:23 Node thr=#<Thread:0x007f0682d93d40> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=1138d
2015-07-21 00:19:33 Node thr=#<Thread:0x007f84d2193d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=43310
2015-07-21 00:22:43 Node thr=#<Thread:0x007f6009593d58> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=b643a
2015-07-21 00:25:53 Node thr=#<Thread:0x007f64f3193d40> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=nwmongw.wakame-vdc-1box, token=750c1
```

**Comment by hansode** [comment]
`update_alarm` also will crash `collector` and `nwmongw`.

hva.log:

```
2015-07-21 00:32:10 JobContext thr=JobWorker[0/1] [INFO]: Job complete 81dcbdb23f9242fff2bc0d4863f5e06cb419a3a7 (Local ID: 81dcbdb23f9242fff2bc0d4863f5e06cb419a3a7)[ update_alarm ]: 0.12720161 sec
```

**Comment by t-iwano** [comment]
update_alarm と delete_alarmでタイムアウトしている。
```
2015-09-24 14:20:18 JobContext thr=JobWorker[0/1] [INFO]: Job start 9e748f8e34b9e196678a53f87fa88b6b46a9b616 (Local ID: 9e748f8e34b9e196678a53f87fa
88b6b46a9b616)[ update_alarm ]
2015-09-24 14:23:22 JobContext thr=JobWorker[0/1] [ERROR]: Job failed 9e748f8e34b9e196678a53f87fa88b6b46a9b616 [ update_alarm ]: timeout
2015-09-24 14:23:22 JobContext thr=JobWorker[0/1] [ERROR]: Caught Isono::NodeModules::RpcChannel::RpcError: timeout
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/rpc_channel.rb:466:in `wait'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/rpc_channel.rb:153:in `request'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/alarm_config_updater.rb:41:in `get_alarms'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/alarm_config_updater.rb:24:in `update_alarm'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/object_method.rb:15:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/object_method.rb:15:in `call'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/alarm_config_updater.rb:15:in `block (3 levels) in <class:AlarmConfigUpdater>'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/map.rb:52:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/map.rb:52:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/builder.rb:36:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/job.rb:59:in `block (2 levels) in call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/job_worker.rb:67:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/job_worker.rb:67:in `block in start'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `block (2 levels) in initialize'
```

```
b713dae398f83c7c)[ delete_alarm ]: 0.094377688 sec
2015-09-24 14:23:32 ThreadPool thr=InstanceMonitor[0/1] [ERROR]: Caught Isono::NodeModules::RpcChannel::RpcError: timeout
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/rpc_channel.rb:466:in `wait'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/rpc_channel.rb:153:in `request'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/instance_monitor.rb:31:in `check_instance'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/node_modules/instance_monitor.rb:12:in `block (3 levels) in <class:InstanceMonitor>'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `call'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `block (2 levels) in initialize'
```

**Comment by t-iwano** [comment]
/var/log/wakame-vdc/collector.log

hva.logのタイムアウトと同じ時にcollectorが再起動している。
```
I, [2015-09-24T14:20:05.520165 #1972]  INFO -- AlarmCollector: event_caught: ["i-alwomgp6"]
2015-09-24 14:20:22 Node thr=#<Thread:0x007f8628993d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=collector.master, token=8733c
I, [2015-09-24T14:23:26.853847 #17383]  INFO -- HvaCollector: finalize_instance(i-alwomgp6) terminated at=2015-09-24 05:23:26 UTC
I, [2015-09-24T14:23:26.871607 #17383]  INFO -- EventHook: event caught: ["i-alwomgp6"]
I, [2015-09-24T14:23:26.894782 #17383]  INFO -- AlarmCollector: event_caught: ["i-alwomgp6"]
I, [2015-09-24T14:23:26.895789 #17383]  INFO -- AlarmCollector: event_caught: ["i-alwomgp6"]
2015-09-24 14:23:31 Node thr=#<Thread:0x007f9bfad93d50> [INFO]: Started : AMQP Server=amqp://127.0.0.1/, ID=collector.master, token=b7e62
```

**Comment by t-iwano** [comment]
```
[centos@wakame-vdc-1box node_modules]$ sudo cat /var/log/messages | grep vdc-collector
Sep 24 14:20:18 wakame-vdc-1box init: vdc-collector main process (1972) killed by HUP signal
Sep 24 14:20:18 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 14:23:27 wakame-vdc-1box init: vdc-collector main process (17383) killed by HUP signal
Sep 24 14:23:27 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:08:05 wakame-vdc-1box init: vdc-collector main process (1952) terminated with status 1
Sep 24 19:08:07 wakame-vdc-1box init: vdc-collector main process (4870) terminated with status 1
Sep 24 19:08:07 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:08:10 wakame-vdc-1box init: vdc-collector main process (4894) terminated with status 1
Sep 24 19:08:10 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:08:13 wakame-vdc-1box init: vdc-collector main process (4912) terminated with status 1
Sep 24 19:08:13 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:08:15 wakame-vdc-1box init: vdc-collector main process (4931) terminated with status 1
Sep 24 19:08:15 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:08:18 wakame-vdc-1box init: vdc-collector main process (4951) terminated with status 1
Sep 24 19:08:18 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:08:20 wakame-vdc-1box init: vdc-collector main process (4975) terminated with status 1
Sep 24 19:08:20 wakame-vdc-1box init: vdc-collector respawning too fast, stopped
Sep 24 19:14:15 wakame-vdc-1box init: vdc-collector main process (6114) terminated with status 1
Sep 24 19:16:35 wakame-vdc-1box init: vdc-collector main process (8127) killed by HUP signal
Sep 24 19:16:35 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:19:42 wakame-vdc-1box init: vdc-collector main process (10497) killed by HUP signal
Sep 24 19:19:42 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:32:14 wakame-vdc-1box init: vdc-collector main process (12111) killed by HUP signal
Sep 24 19:32:14 wakame-vdc-1box init: vdc-collector main process ended, respawning
Sep 24 19:35:22 wakame-vdc-1box init: vdc-collector main process (13440) killed by HUP signal
Sep 24 19:35:22 wakame-vdc-1box init: vdc-collector main process ended, respawning
```

**Comment by t-iwano** [comment]
alarm_config_updater.rb
```
     70       fluent = Dcmgr::Drivers::Fluent.new
     71       fluent.set_alarms(alm)
     72       fluent.generate_config
     73       fluent.reload
     74     end
     75
```

**Comment by t-iwano** [comment]
drivers/fluent.rb

```
     45       def reload
     46         if Dcmgr::Configurations.hva.logging_service_reload
     47           sh("#{Dcmgr::Configurations.hva.logging_service_reload}")
     48           logger.info("Reload fluent with #{@output_file}")
     49         else
     50           logger.error("Failed to reload fluent. Not found #{Dcmgr::Configurations.hva.logging_service_reload}")
     51         end
     52       end
```

**Comment by t-iwano** [comment]
configurations/hva.rb
```
    226       param :use_logging_service, :default=>false
    227       param :logging_service_host_ip, :default =>'127.0.0.2'
    228       param :logging_service_ip, :default =>'169.254.169.253'
    229       param :logging_service_port, :default => 8888
    230       param :logging_service_conf, :default => '/var/lib/wakame-vdc/fluent.conf'
    231       param :logging_service_reload, :default => '/etc/init.d/td-agent reload'
    232       param :logging_service_max_read_message_bytes, :default => -1
    233       param :logging_service_max_match_count, :default => -1
```

**Comment by t-iwano** [comment]
/etc/init.d/td-agent

```
     90     reload)
     91         killproc $td_agent -HUP
     92         ;;
```

**Comment by t-iwano** [comment]
/etc/init.d/functions

```
    271 killproc() {
    272         local RC killlevel= base pid pid_file= delay
    273
    274         RC=0; delay=3
    275         # Test syntax.
    276         if [ "$#" -eq 0 ]; then
    277                 echo $"Usage: killproc [-p pidfile] [ -d delay] {program} [-signal]"
    278                 return 1
    279         fi
    280         if [ "$1" = "-p" ]; then
    281                 pid_file=$2
    282                 shift 2
    283         fi
    284         if [ "$1" = "-d" ]; then
    285                 delay=$2
    286                 shift 2
    287         fi
    288
    289
    290         # check for second arg to be kill level
    291         [ -n "${2:-}" ] && killlevel=$2
    292
    293         # Save basename.
    294         base=${1##*/}
    295
    296         # Find pid.
    297         __pids_var_run "$1" "$pid_file"
    298         RC=$?
    299         if [ -z "$pid" ]; then
    300                 if [ -z "$pid_file" ]; then
    301                         pid="$(__pids_pidof "$1")"
    302                 else
    303                         [ "$RC" = "4" ] && { failure $"$base shutdown" ; return $RC ;}
    304                 fi
    305         fi
    306
```

**Comment by t-iwano** [comment]
```
    173 # Output PIDs of matching processes, found using pidof
    174 __pids_pidof() {
    175         pidof -c -o $$ -o $PPID -o %PPID -x "$1" || \
    176                 pidof -c -o $$ -o $PPID -o %PPID -x "${1##*/}"
    177 }
```

**Comment by t-iwano** [comment]
td-agentのreload時に呼ばれているコマンド

```
killproc /usr/lib64/fluent/ruby/bin/ruby -HUP
```

**Comment by t-iwano** [comment]
```
[centos@wakame-vdc-1box node_modules]$ pidof -c -o $$ -o $PPID -o %PPID -x /usr/lib64/fluent/ruby/bin/ruby
34734 34731 34098 34094 25344
```

**Comment by t-iwano** [comment]
```
[centos@wakame-vdc-1box node_modules]$ initctl list | grep vdc-
vdc-admin start/running, process 2070
vdc-natbox stop/waiting
vdc-sta stop/waiting
vdc-hva start/running, process 25344
vdc-collector start/running, process 34098
vdc-nwmongw start/running, process 34094
vdc-fluentd stop/waiting
vdc-dolphin start/running, process 34096
vdc-bksta stop/waiting
vdc-hva-worker stop/waiting
vdc-webui start/running, process 2073
vdc-dcmgr start/running, process 2074
```

**Comment by t-iwano** [comment]
```
[centos@wakame-vdc-1box node_modules]$ ps -ef | grep td-agent
td-agent   34731       1  0 16:50 ?        00:00:00 /usr/lib64/fluent/ruby/bin/ruby /usr/sbin/td-agent --group td-agent --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
td-agent   34734   34731  0 16:50 ?        00:00:02 /usr/lib64/fluent/ruby/bin/ruby /usr/sbin/td-agent --group td-agent --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
centos     35709   16633  0 17:26 pts/3    00:00:00 grep td-agent
```

**Comment by t-iwano** [comment]
1box環境だとtd-agentのreload時に以下のプロセスも一緒にrestartされてしまっている。

* vdc-collector
* vdc-hva
* vdc-nwmongw

**Comment by t-iwano** [comment]
今回のrpc time out問題の原因は↑

**Comment by hansode** [comment]
恒久対策としては、
Flientdを各agentから起動する必要があるのか、、、。

**Comment by hansode** [comment]
後はfluentdクライアントにretryを実装だろうか。

**Comment by t-iwano** [comment]
前にかつおさんがやろうとしていたvdc-fluentに移してhvaからsuperviseするのがよいと思われます。

**Comment by Metallion** [comment]
Done https://github.com/axsh/wakame-vdc/pull/735
