### ISSUE TITLE
Wakame-vdc cannot terminate an instance that is still initializing

### ISSUE THREAD

**Issue by triggers** [axsh/wakame-vdc#640]
### Problem:

After an instance is launched, it first goes through an "initializing"
state.  Once KVM starts running, the state is changed to "running".
Wakame-vdc currently pretends to terminate an instance when it is in
the "initializing" phase, but the instance continues to initialize
and change to running state.

For Windows instances, this is a problem because the initializing
phase can be long.  Windows instances (unlike Linux instances)
actually have to boot and configure during this time.  If something
hangs in the wakame-init scripts, then the user must wait until the
amount of time specified in the password_generation_timeout parameter
(in hva.conf) passes.  Also, if the user mistakenly creates an
instance, they will have to needlessly wait before they can undo their
action.

This problem is bigger in nested KVM testing environments, because
Windows boot times and the value of password_generation_timeout can be
more than an hour.

**Comment by triggers** [comment]
### Example: 

Create instance:

```
/ssh:m47-31: #$ http_proxy= MUSSEL_RC=./MUSSEL_RC_WINDOWS ~/wakame-vdc-mita/client/mussel/mussel.sh instance create --ssh-key-id ssh-cxkqxlwx  --vifs=./vifs.txt
---
:id: i-10u9tnej
:account_id: a-shpoolxx
:host_node: 
:cpu_cores: 2
:memory_size: 2048
:arch: x86_64
:image_id: wmi-windows2012r2
:created_at: 2015-06-29 09:28:24.000000000 Z
:updated_at: 2015-06-29 09:28:24.177518239 Z
:terminated_at: 
:deleted_at: 
:state: scheduling
:status: init
:ssh_key_pair:
  :uuid: ssh-cxkqxlwx
  :display_name: mykeypair
:volume:
- :vol_id: vol-7z4k361d
  :state: scheduling
:vif: []
:hostname: 10u9tnej
:ha_enabled: 0
:hypervisor: kvm
:display_name: ''
:service_type: std
:monitoring:
  :enabled: false
  :mail_address: []
  :items: {}
:labels:
- :resource_uuid: i-10u9tnej
  :name: monitoring.enabled
  :value_type: 1
  :value: 'false'
  :created_at: 2015-06-29 09:28:24.000000000 Z
  :updated_at: 2015-06-29 09:28:24.000000000 Z
:boot_volume_id: vol-7z4k361d
```

Try to delete it while wakame is still doing "gzip -d":

```
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "GET" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml" | grep state
:state: initializing
  :state: pending
/ssh:m47-31: #$ 
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "DELETE" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml"
---
- i-10u9tnej
```

(It did not delete, gzip is still running)

Try to delete it while wakame is still doing first boot with qemu:

```
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "GET" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml" | grep state
:state: initializing
  :state: attached
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "DELETE" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml"
---
- i-10u9tnej
```

(It did not delete, qemu is is still running)

Successfully delete after second boot:

```
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "GET" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml" | grep state
:state: running
  :state: attached
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "DELETE" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml"
---
- i-10u9tnej
```

Now delete correctly returns an error:

```
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "GET" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml" | grep state
:state: terminated
  :state: deleted
/ssh:m47-31: #$ http_proxy= "curl" "-fsSkL" "-H" "X_VDC_ACCOUNT_UUID:a-shpoolxx" "-X" "DELETE" "http://10.126.5.17:9001/api/12.03/instances/i-10u9tnej.yml"
curl: (22) The requested URL returned error: 400 Bad Request
```

**Comment by triggers** [comment]
### Related stack trace in hva.log:

```
2015-06-29 18:34:04 JobContext thr=JobWorker[0/1] [INFO]: Job start ef5875ecca1747402342fcd05076ec4759209526 (Local ID: ef5875ecca1747402342fcd05076ec4759209526)[ terminate ]
2015-06-29 18:34:04 JobContext thr=JobWorker[0/1] [ERROR]: Job failed ef5875ecca1747402342fcd05076ec4759209526 [ terminate ]: Invalid instance state: initializing
2015-06-29 18:34:04 JobContext thr=JobWorker[0/1] [ERROR]: Caught RuntimeError: Invalid instance state: initializing
	/opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/rpc/hva_handler.rb:398:in `block in <class:HvaHandler>'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/proc.rb:25:in `instance_eval'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/proc.rb:25:in `call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/map.rb:52:in `call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/map.rb:52:in `call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/builder.rb:36:in `call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/rack/job.rb:59:in `block (2 levels) in call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/job_worker.rb:67:in `call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/node_modules/job_worker.rb:67:in `block in start'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `call'
	/opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/2.0.0/gems/isono-0.2.20/lib/isono/thread_pool.rb:32:in `block (2 levels) in initialize'
```
