### ISSUE TITLE
register ubuntu image parameter

### ISSUE THREAD

**Issue by t-iwano** [axsh/wakame-vdc#745]
wakame-vdcに登録するubuntu imageのparameterを作る。
- ubuntu-14.04.3-x86_64-30g-passwd-login-disabled.raw.tgz
- ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw.tgz

**Comment by t-iwano** [comment]
ubuntu-14.04.3-x86_64-30g-passwd-login-disabled.raw.tgz

```
backupobject add --uuid bo-ubuntu14043pld --display-name "ubuntu 14.04.3 passwd login disabled" --storage-id bkst-local --object-key ubuntu-14.04.3-x86_64-30g-passwd-login-disabled.raw.tgz --container-format tgz --size=312433664 --allocation-size=312433883 --checksum=cbb11ebbb1858b52220150f96762213d

image add local bo-ubuntu14043pld --account-id a-shpoolxx --uuid wmi-ubuntu14043pld --root-device label:root --display-name "ubuntu 14.04.3 passwd login disabled"
```

**Comment by t-iwano** [comment]
ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw.tgz

```
backupobject add --uuid bo-ubuntu14043ple --display-name "ubuntu 14.04.3 passwd login enabled" --storage-id bkst-local --object-key ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw.tgz --container-format tgz --size=312416768 --allocation-size=312417133 --checksum=f07d64f8bef8fa02f526ea208d04df9d

image add local bo-ubuntu14043ple --account-id a-shpoolxx --uuid wmi-ubuntu14043ple --root-device label:root --display-name "ubuntu 14.04.3 passwd login enabled"
```

**Comment by Metallion** [comment]
I got this error when trying out the image:

```
2015-10-08 15:20:48 JobContext thr=JobWorker[0/1] [ERROR]: Caught RuntimeError: root device does not exist label:root
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/hypervisor/linux_hypervisor/linux_container.rb:114:in `mount_root_image'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/hypervisor/linux_hypervisor/linux_container/openvz.rb:136:in `run_instance'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:178:in `call'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:178:in `invoke!'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:249:in `invoke'
```

```
[15:24:46] metallion@castella  (~/Downloads) > sudo kpartx -av ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw
add map loop0p1 (254:0): 0 58591734 linear /dev/loop0 63

[15:25:52] metallion@castella  (~/Downloads) > sudo lsblk -o name,mountpoint,label,size,uuid

NAME      MOUNTPOINT LABEL   SIZE UUID
...
loop0                       29.3G 
└─loop0p1                     28G 4dab6d7e-2909-47e7-9be1-e63b90618d3d
```

**Comment by Metallion** [comment]
UUIDで登録したら、動いた。でもなぜかHDスペースは2ギガしかない。これはイメージの問題か、Wakame-vdcの問題かどうか分からない。

```
ubuntu@36tbvu5m:~$ df -h .
Filesystem       Size  Used Avail Use% Mounted on
/vz/private/104  2.0G  776M  1.3G  38% /
```

**Comment by t-iwano** [comment]
kvmで起動するとちゃんと30gあるように見える。

```
ubuntu@h0vzhr22:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        28G  820M   26G   4% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            235M  4.0K  235M   1% /dev
tmpfs            50M  276K   49M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            246M     0  246M   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/sdb1       9.0M   94K  8.9M   2% /metadata
```

**Comment by Metallion** [comment]
なるほど。OpenVZの問題か。

**Comment by t-iwano** [comment]
```
ubuntu@z97z9wge:~$ sudo e2label /dev/sda1
root
```

**Comment by t-iwano** [comment]
```
backupobject add --uuid bo-ubuntu14043pld --display-name "ubuntu 14.04.3 passwd login disabled" --storage-id bkst-demo1 --object-key ubuntu-14.04.3-x86_64-30g-passwd-login-disabled.raw.tgz --container-format tgz --size=312551936 --allocation-size=312552233 --checksum=8b4a076363e3e03f6ade2b5b505435bf

image add local bo-ubuntu14043pld --account-id a-shpoolxx --uuid wmi-ubuntu14043pld --root-device label:root --display-name "ubuntu 14.04.3 passwd login disabled"

backupobject add --uuid bo-ubuntu14043ple --display-name "ubuntu 14.04.3 passwd login enabled" --storage-id bkst-demo1 --object-key ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw.tgz --container-format tgz --size=312530432 --allocation-size=312530604 --checksum=81bb27d621f2d1e90ce24625a1dcb311

image add local bo-ubuntu14043ple --account-id a-shpoolxx --uuid wmi-ubuntu14043ple --root-device label:root --display-name "ubuntu 14.04.3 passwd login enabled"
```

**Comment by Metallion** [comment]
Continued here: https://github.com/axsh/wakame-vdc/issues/688
